# Generated by Django 2.2.17 on 2021-02-03 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=30)),
                ('producent', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('macaddress', models.CharField(max_length=20)),
                ('ipaddress', models.CharField(max_length=20)),
            ],
        ),
    ]
