# Generated by Django 2.2.17 on 2021-02-05 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='sessions',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='status',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='device',
            name='ipaddress',
            field=models.GenericIPAddressField(),
        ),
    ]
