# Generated by Django 2.2.17 on 2021-02-22 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0002_auto_20210205_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='community_name',
            field=models.CharField(default='none', max_length=50),
            preserve_default=False,
        ),
    ]
