# Generated by Django 2.2.17 on 2021-03-15 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0005_auto_20210314_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='producent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='WebMonitor.Producent'),
        ),
    ]
