# Generated by Django 2.2.17 on 2021-03-15 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0008_auto_20210315_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='producent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='WebMonitor.Producent'),
        ),
    ]
