# Generated by Django 2.2.17 on 2021-03-15 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0011_remove_device_producent'),
    ]

    operations = [
        migrations.AddField(
            model_name='producent',
            name='producent_id',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
