# Generated by Django 2.2.17 on 2021-03-15 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0012_producent_producent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='producent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='WebMonitor.Producent'),
        ),
    ]
