# Generated by Django 2.2.17 on 2021-03-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0016_auto_20210316_2046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='macaddress',
        ),
        migrations.AlterField(
            model_name='device',
            name='sessions',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
