# Generated by Django 2.2.17 on 2021-03-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0018_firewall_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='zones',
            field=models.ManyToManyField(blank=True, null=True, to='WebMonitor.Zone'),
        ),
    ]
