# Generated by Django 2.2.17 on 2021-03-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0021_auto_20210328_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='producent',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='WebMonitor.Service'),
        ),
    ]
