# Generated by Django 2.2.17 on 2021-04-01 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0023_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
