# Generated by Django 2.2.17 on 2021-04-02 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0024_session_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='start_time',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
