# Generated by Django 2.2.17 on 2021-04-02 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0026_auto_20210402_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='producent',
            name='freestorage_alloc_opOID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producent',
            name='freestorage_alloc_osOID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producent',
            name='storage_alloc_opOID',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producent',
            name='storage_alloc_osOID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
