# Generated by Django 2.2.17 on 2021-04-03 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0027_auto_20210402_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='free_storage',
        ),
        migrations.RemoveField(
            model_name='producent',
            name='freestorage_alloc_opOID',
        ),
        migrations.RemoveField(
            model_name='producent',
            name='freestorage_alloc_osOID',
        ),
        migrations.RemoveField(
            model_name='producent',
            name='freestorage_opOID',
        ),
        migrations.RemoveField(
            model_name='producent',
            name='freestorage_osOID',
        ),
        migrations.AddField(
            model_name='device',
            name='used_storage',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='producent',
            name='usedstorage_alloc_opOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producent',
            name='usedstorage_alloc_osOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producent',
            name='usedstorage_opOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producent',
            name='usedstorage_osOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producent',
            name='storage_alloc_opOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producent',
            name='storage_alloc_osOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producent',
            name='storage_opOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producent',
            name='storage_osOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producent',
            name='temperature_opOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producent',
            name='temperature_osOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producent',
            name='transfer_opOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producent',
            name='transfer_osOID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
