# Generated by Django 2.2.17 on 2021-04-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0029_auto_20210403_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='free_storage',
            field=models.FloatField(null=True),
        ),
    ]
