# Generated by Django 2.2.17 on 2021-04-03 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0030_device_free_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='free_storage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='storage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='used_storage',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
