# Generated by Django 2.2.17 on 2021-04-07 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0033_auto_20210407_2133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='nat_ipaddress',
        ),
        migrations.AlterField(
            model_name='device',
            name='free_storage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='storage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='used_storage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
