# Generated by Django 2.2.17 on 2021-04-10 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0035_auto_20210409_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cpu_load',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='temperature',
            field=models.IntegerField(editable=False, null=True),
        ),
    ]
