# Generated by Django 2.2.17 on 2021-04-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0036_auto_20210410_1520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='services',
        ),
        migrations.RemoveField(
            model_name='service',
            name='port',
        ),
        migrations.AddField(
            model_name='service',
            name='device',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='WebMonitor.Device'),
        ),
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(editable=False, null=True),
        ),
    ]
