# Generated by Django 2.2.17 on 2021-04-11 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0038_auto_20210410_1716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='status',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(editable=False, max_length=50, null=True),
        ),
    ]
