# Generated by Django 2.2.17 on 2021-04-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0040_auto_20210411_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='cpu_load_critical',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='cpu_load_warning',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='temperature_critical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='temperature_warning',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
