# Generated by Django 2.2.17 on 2021-04-12 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0041_auto_20210412_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='used_storage_percentage',
            field=models.FloatField(blank=True, default=1.0, null=True),
        ),
    ]
