# Generated by Django 2.2.17 on 2021-05-02 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0046_auto_20210417_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='session_count_critical',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='session_count_warning',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
