# Generated by Django 2.2.17 on 2021-05-02 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0047_auto_20210502_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='alert_couse',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
