# Generated by Django 2.2.17 on 2021-05-02 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0050_auto_20210502_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='alert_couse',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 2, 21, 3, 42, 944382)),
        ),
    ]
