# Generated by Django 2.2.17 on 2021-05-03 21:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0052_auto_20210503_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='used_storage_percentage',
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 23, 38, 1, 926653)),
        ),
    ]
