# Generated by Django 2.2.17 on 2021-05-03 22:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0053_auto_20210503_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 0, 35, 54, 186773)),
        ),
    ]
