# Generated by Django 2.2.17 on 2021-05-03 22:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0054_auto_20210504_0035'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='used_storage_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='session',
            name='start_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 4, 0, 49, 34, 975187)),
        ),
    ]
