# Generated by Django 2.2.17 on 2021-05-03 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0056_auto_20210504_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='used_storage_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=10, null=True),
        ),
    ]
