# Generated by Django 2.2.17 on 2021-05-16 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0058_firewall_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='cpu_osOID',
        ),
        migrations.RemoveField(
            model_name='device',
            name='status_osOID',
        ),
        migrations.RemoveField(
            model_name='device',
            name='storage_alloc_osOID',
        ),
        migrations.RemoveField(
            model_name='device',
            name='storage_osOID',
        ),
        migrations.RemoveField(
            model_name='device',
            name='temperature_osOID',
        ),
        migrations.RemoveField(
            model_name='device',
            name='usedstorage_osOID',
        ),
        migrations.RemoveField(
            model_name='service',
            name='service_osOID',
        ),
    ]
