# Generated by Django 2.2.17 on 2021-05-23 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0059_auto_20210516_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producent',
            name='producent_id',
        ),
        migrations.AddField(
            model_name='firewall',
            name='producent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='WebMonitor.Producent'),
        ),
    ]
