# Generated by Django 2.2.17 on 2021-05-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0061_auto_20210524_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='producent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='WebMonitor.Producent'),
        ),
    ]
