# Generated by Django 2.2.17 on 2021-05-24 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebMonitor', '0062_auto_20210524_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewall',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=200),
            preserve_default=False,
        ),
    ]
